/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * EDF Reader API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EdfChannelSignal,
  EdfFileContent,
  EdfFileSummary,
  GetChannelSignalParams,
  GetFileByNameParams
} from './generated.schemas';

import { customAxios } from './axios-instance';




/**
 * @summary List all EDF files in the directory with their status
 */
export const getFilesList = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxios<EdfFileSummary[]>(
      {url: `/files`, method: 'GET', signal
    },
      );
    }
  



export const getGetFilesListQueryKey = () => {
    return [
    `/files`
    ] as const;
    }

    
export const getGetFilesListQueryOptions = <TData = Awaited<ReturnType<typeof getFilesList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilesList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFilesListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFilesList>>> = ({ signal }) => getFilesList(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFilesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFilesListQueryResult = NonNullable<Awaited<ReturnType<typeof getFilesList>>>
export type GetFilesListQueryError = unknown


export function useGetFilesList<TData = Awaited<ReturnType<typeof getFilesList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilesList>>,
          TError,
          Awaited<ReturnType<typeof getFilesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilesList<TData = Awaited<ReturnType<typeof getFilesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilesList>>,
          TError,
          Awaited<ReturnType<typeof getFilesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilesList<TData = Awaited<ReturnType<typeof getFilesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilesList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all EDF files in the directory with their status
 */

export function useGetFilesList<TData = Awaited<ReturnType<typeof getFilesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilesList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFilesListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get the parsed content of a single EDF file by name
 */
export const getFileByName = (
    params: GetFileByNameParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<EdfFileContent>(
      {url: `/files/content`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetFileByNameQueryKey = (params?: GetFileByNameParams,) => {
    return [
    `/files/content`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetFileByNameQueryOptions = <TData = Awaited<ReturnType<typeof getFileByName>>, TError = void | void>(params: GetFileByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFileByName>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFileByNameQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFileByName>>> = ({ signal }) => getFileByName(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFileByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFileByNameQueryResult = NonNullable<Awaited<ReturnType<typeof getFileByName>>>
export type GetFileByNameQueryError = void | void


export function useGetFileByName<TData = Awaited<ReturnType<typeof getFileByName>>, TError = void | void>(
 params: GetFileByNameParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFileByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFileByName>>,
          TError,
          Awaited<ReturnType<typeof getFileByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFileByName<TData = Awaited<ReturnType<typeof getFileByName>>, TError = void | void>(
 params: GetFileByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFileByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFileByName>>,
          TError,
          Awaited<ReturnType<typeof getFileByName>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFileByName<TData = Awaited<ReturnType<typeof getFileByName>>, TError = void | void>(
 params: GetFileByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFileByName>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the parsed content of a single EDF file by name
 */

export function useGetFileByName<TData = Awaited<ReturnType<typeof getFileByName>>, TError = void | void>(
 params: GetFileByNameParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFileByName>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFileByNameQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get the sample data of a single channel
 */
export const getChannelSignal = (
    params: GetChannelSignalParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<EdfChannelSignal>(
      {url: `/files/signal`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetChannelSignalQueryKey = (params?: GetChannelSignalParams,) => {
    return [
    `/files/signal`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetChannelSignalQueryOptions = <TData = Awaited<ReturnType<typeof getChannelSignal>>, TError = void | void>(params: GetChannelSignalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChannelSignal>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChannelSignalQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChannelSignal>>> = ({ signal }) => getChannelSignal(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChannelSignal>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetChannelSignalQueryResult = NonNullable<Awaited<ReturnType<typeof getChannelSignal>>>
export type GetChannelSignalQueryError = void | void


export function useGetChannelSignal<TData = Awaited<ReturnType<typeof getChannelSignal>>, TError = void | void>(
 params: GetChannelSignalParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChannelSignal>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelSignal>>,
          TError,
          Awaited<ReturnType<typeof getChannelSignal>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChannelSignal<TData = Awaited<ReturnType<typeof getChannelSignal>>, TError = void | void>(
 params: GetChannelSignalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChannelSignal>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelSignal>>,
          TError,
          Awaited<ReturnType<typeof getChannelSignal>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetChannelSignal<TData = Awaited<ReturnType<typeof getChannelSignal>>, TError = void | void>(
 params: GetChannelSignalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChannelSignal>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the sample data of a single channel
 */

export function useGetChannelSignal<TData = Awaited<ReturnType<typeof getChannelSignal>>, TError = void | void>(
 params: GetChannelSignalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getChannelSignal>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetChannelSignalQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




