/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * EDF Reader API
 * OpenAPI spec version: 1.0.0
 */
export type EdfFileStatus = typeof EdfFileStatus[keyof typeof EdfFileStatus];


 
export const EdfFileStatus = {
  VALID: 'VALID',
  CORRUPT: 'CORRUPT',
  MISSING_METADATA: 'MISSING_METADATA',
  INCONSISTENT_HEADER: 'INCONSISTENT_HEADER',
} as const;

export interface EdfFileSummary {
  fileName: string;
  status: EdfFileStatus;
  recordingDate?: string;
}

export interface EdfFileContent {
  fileName: string;
  identifier?: string;
  partiallyReadable: boolean;
  recordingDate: string;
  patientName?: string;
  numberOfChannels: number;
  channels: EdfChannel[];
  recordingLengthSeconds: number;
  numberOfAnnotations: number;
}

export interface EdfChannel {
  name: string;
  type?: string;
  physicalDimension?: string;
  samplingFrequency?: number;
}

export type GetFileByNameParams = {
name: string;
};

